package com.team2.wellness.engagement.ai.application;

import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
import com.team2.wellness.common.api.ApiException; import com.team2.wellness.engagement.ai.domain.AiGenerationJob; import com.team2.wellness.engagement.ai.persistence.AiGenerationJobRepository; import com.team2.wellness.engagement.chat.application.ChatService; import com.team2.wellness.engagement.chat.domain.ChatRoom; import com.team2.wellness.engagement.notification.persistence.NotificationRepository; import com.team2.wellness.engagement.port.out.*; import java.time.*; import java.util.*; import org.junit.jupiter.api.*; import org.springframework.transaction.*; import org.springframework.transaction.support.*;
class AiGenerationServiceTest {
 AiGenerationJobRepository jobs=mock(AiGenerationJobRepository.class); CoreAccessPort core=mock(CoreAccessPort.class); MediaStoragePort storage=mock(MediaStoragePort.class); ImageGenerationPort images=mock(ImageGenerationPort.class); ChatService chat=mock(ChatService.class); NotificationRepository notifications=mock(NotificationRepository.class); RealtimePublisherPort realtime=mock(RealtimePublisherPort.class); AiGenerationService service; UUID requester=UUID.randomUUID(),target=UUID.randomUUID(),occurrence=UUID.randomUUID();
 @BeforeEach void set(){service=new AiGenerationService(jobs,core,storage,images,chat,notifications,realtime,new SafeFuturePromptBuilder(),new TransactionTemplate(new NoopTx())); when(core.areAcceptedFriends(requester,target)).thenReturn(true); when(core.hasAiImageConsent(target)).thenReturn(true); when(core.getMissedRoutineOccurrence(occurrence,target)).thenReturn(Optional.of(new CoreAccessPort.MissedRoutineOccurrence(occurrence,UUID.randomUUID(),target,"물 마시기","수분",5,LocalDate.of(2026,8,18))));}
 @Test void consentOrMissingOccurrenceBlocksRequest(){when(core.hasAiImageConsent(target)).thenReturn(false); assertThatThrownBy(()->service.request(requester,target,occurrence,"x")).isInstanceOf(ApiException.class); verify(jobs,never()).save(any());}
 @Test void dailyLimitIsEnforced(){when(jobs.countByRequesterIdAndCreatedAtGreaterThanEqual(eq(requester),any())).thenReturn(3L); assertThatThrownBy(()->service.request(requester,target,occurrence,"x")).isInstanceOf(ApiException.class);}
 @Test void provider429IsQueuedForRetry(){AiGenerationJob job=new AiGenerationJob(requester,target,occurrence,"x"); when(jobs.findReady(any(),any())).thenReturn(List.of(job)); when(storage.findFaceAsset(target)).thenReturn(Optional.of(new MediaStoragePort.StoredMedia("face","image/png"))); when(storage.read("face")).thenReturn(new byte[]{1}); when(images.generate(any())).thenThrow(new ImageGenerationException("OPENAI_RATE_LIMIT")); when(jobs.findById(job.getId())).thenReturn(Optional.of(job)); service.processNext(); assertThat(job.getStatus()).isEqualTo(AiGenerationJob.Status.QUEUED); assertThat(job.getAttemptCount()).isEqualTo(1);}
 @Test void successCreatesRoutineAwarePromptChatMessageAndNotification(){AiGenerationJob job=new AiGenerationJob(requester,target,occurrence,"x"); when(jobs.findReady(any(),any())).thenReturn(List.of(job)); when(storage.findFaceAsset(target)).thenReturn(Optional.of(new MediaStoragePort.StoredMedia("face","image/png"))); when(storage.read("face")).thenReturn(new byte[]{1}); when(images.generate(any())).thenReturn(new ImageGenerationPort.ImageResult(new byte[]{2},"image/png")); when(storage.storeAiOutput(eq(target),any(),eq("image/png"))).thenReturn(new MediaStoragePort.StoredMedia("out","image/png")); when(jobs.findById(job.getId())).thenReturn(Optional.of(job)); when(chat.createDirect(requester,target)).thenReturn(ChatRoom.direct(requester,target)); service.processNext(); assertThat(job.getStatus()).isEqualTo(AiGenerationJob.Status.SUCCEEDED); verify(images).generate(argThat(command -> command.prompt().contains("<title>물 마시기</title>") && command.prompt().contains("<category>수분</category>") && command.prompt().contains(">5</missed_occurrences"))); verify(chat).send(eq(requester),any(),argThat(command -> command.content().contains("최근 5번"))); verify(notifications).save(any());}
 static class NoopTx implements PlatformTransactionManager { public TransactionStatus getTransaction(TransactionDefinition d){return new SimpleTransactionStatus();} public void commit(TransactionStatus s){} public void rollback(TransactionStatus s){} }
}
